### PR TITLE
Replace bash script with `/usr/bin/env which`

### PR DESCRIPTION
**Pull request by mava**
This is not important, and I’m probably overlooking something, and if it ain’t broke don’t fix it, ….
But it seems that the `find_tool.sh` script could be avoided by calling `/usr/bin/env which` instead.

### CODE REVIEW

**Comment by flyx** [comment]
`find_tool.sh` is unnecessary for setups that use system-wide installations in `/usr/local/bin` (which is always in the PATH) or which are registered in `/etc/paths.d` (this is true for MacTeX iirc). However with per-user software installation (e.g. via [Nix home-manager](https://github.com/nix-community/home-manager), which is what I use) the directory is not in the system-wide PATH and therefore the extension needs to load the login shell's configuration to be able to find the utility. There is no single source of truth for the user-specific PATH, as this is shell-dependent and may be eg in `~/.bash_profile`, `~/.zshrc` or `~/.config/fish/config.fish`. This is why `find_tool.sh` runs the login shell and uses `which` in there.

**Comment by mava** [comment]
Thank you for the explanation! Would [this](https://docs.nova.app/api-reference/process/#running-processes-in-a-shell) fix it?

**Comment by flyx** [comment]
The problem is getting the `--login` argument to the shell itself. You can only set the shell path, and the arguments to the command you want to run. Without `--login`, the shell won't parse its respective configuration file.

**Comment by mava** [comment]
Thank you! Weird, though: it seems to work here on my end?! I just tried to add a directory (with a bogus `latexmk`)  in front of my `PATH` only in my `~/.zshrc` and not system-wide, and the extension found the bogus `latexmk`. 🤷

**Comment by flyx** [comment]
Interesting. Perhaps the shell command does `--login` implicitly? I'll test that later.

**Comment by mava** [comment]
In fact, it seems that the `shell: true` option is unnecessary and everything works with the [first version above](https://github.com/flyx/TeX.novaextension/pull/5/commits/6307dab55480bf5afaa8815bf89575a78bbcd324); calling `/usr/bin/env` does the trick. The *Automatically request environment from login shell* option in Nova’s [Preferences → Tools](https://library.panic.com/nova/preferences/#tools) needs to be selected, though (that’s the default).

**Comment by flyx** [comment]
Wow I never saw that, if Nova does that `find_tool.sh` is indeed superfluous. I assume that option has been added somewhen after I started my project since this didn't work back then. Would you revert the `shell: true` change since it isn't necessary?

**Pull request merged**
